### ISSUE TITLE
ERROR: LoadError: UndefVarError: map_splits_to_tree not defined

### ISSUE THREAD

**Issue by Xiaoman-Wei** [PierreBarrat/RecombTools#21]
Hi TreeKnit team,
 
Thanks for this great approach!
 
When I am testing the TreeKnit on Mac mini (M1 chip) and MacBook pro (M1) by using the example tree files - tree_h3n2_ha.nwk, tree_h3n2_na.nwk. Both of two platforms generated the same error: “ERROR: LoadError: UndefVarError: map_splits_to_tree not defined.”
 
Does anyone know the solution? Thank you in advance!
 
I installed the Julia, TreeKnit and "TreeTools" by following this method: https://pierrebarrat.github.io/TreeKnit.jl/
 
**Command line and error are as bellows:**

% treeknit tree_h3n2_ha.nwk tree_h3n2_na.nwk -o=test_results
Treeknit:
Input trees: tree_h3n2_ha.nwk 	 tree_h3n2_na.nwk
Results directory: test_results
γ: 2.0
ERROR: LoadError: UndefVarError: map_splits_to_tree not defined
Stacktrace:
  [1] getproperty
    @ ./Base.jl:31 [inlined]
  [2] new_splits(tref::TreeTools.Tree{TreeTools.EmptyData}, MCCs::Vector{Vector{String}}, t::TreeTools.Tree{TreeTools.EmptyData})
    @ TreeKnit ~/.julia/packages/TreeKnit/gOfL1/src/mcc_splits.jl:74
  [3] new_splits(MCCs::Vector{Vector{String}}, t1::TreeTools.Tree{TreeTools.EmptyData}, t2::TreeTools.Tree{TreeTools.EmptyData})
    @ TreeKnit ~/.julia/packages/TreeKnit/gOfL1/src/mcc_splits.jl:57
  [4] resolve!(t1::TreeTools.Tree{TreeTools.EmptyData}, t2::TreeTools.Tree{TreeTools.EmptyData}, MCCs::Vector{Vector{String}}; tau::Float64)
    @ TreeKnit ~/.julia/packages/TreeKnit/gOfL1/src/resolving.jl:158
  [5] resolve!(t1::TreeTools.Tree{TreeTools.EmptyData}, t2::TreeTools.Tree{TreeTools.EmptyData}, MCCs::Vector{Vector{String}})
    @ TreeKnit ~/.julia/packages/TreeKnit/gOfL1/src/resolving.jl:157
  [6] treeknit(nwk1::String, nwk2::String; outdir::SubString{String}, gamma::Float64, seq_lengths::String, n_mcmc_it::Int64, naive::Bool, no_likelihood::Bool, no_resolve::Bool, verbose::Bool)
    @ TreeKnit ~/.julia/packages/TreeKnit/gOfL1/src/cli.jl:103
  [7] command_main(ARGS::Vector{String})
    @ TreeKnit ~/.julia/scratchspaces/03f602be-98a1-4bb2-9504-fbd3406624a7/sysimg/libtreeknit.dylib:-1
  [8] command_main()
    @ TreeKnit ~/.julia/packages/Comonicon/AKDtr/src/codegen/julia.jl:88
  [9] top-level scope
    @ ~/.julia/bin/treeknit:15
 [10] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
    @ Base ~/.julia/scratchspaces/03f602be-98a1-4bb2-9504-fbd3406624a7/sysimg/libtreeknit.dylib:-1
 [11] _include(mapexpr::Function, mod::Module, _path::String)
    @ Base ~/.julia/scratchspaces/03f602be-98a1-4bb2-9504-fbd3406624a7/sysimg/libtreeknit.dylib:-1
 [12] include(mod::Module, _path::String)
    @ Base ~/.julia/scratchspaces/03f602be-98a1-4bb2-9504-fbd3406624a7/sysimg/libtreeknit.dylib:-1
 [13] exec_options(opts::Base.JLOptions)
    @ Base ~/.julia/scratchspaces/03f602be-98a1-4bb2-9504-fbd3406624a7/sysimg/libtreeknit.dylib:-1
 [14] _start()
    @ Base ~/.julia/scratchspaces/03f602be-98a1-4bb2-9504-fbd3406624a7/sysimg/libtreeknit.dylib:-1
in expression starting at /Users/xmwei/.julia/bin/treeknit:15

**log file is as bellows:**

/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/cli.jl:64 [Info] Input Newick files: tree_h3n2_ha.nwk 	 tree_h3n2_na.nwk. Reading trees...
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/cli.jl:93 [Info] Parameters: OptArgs
  γ: Float64 2.0
  itmax: Int64 15
  likelihood_sort: Bool true
  resolve: Bool true
  seq_lengths: Array{Int64}((2,)) [1, 1]
  nMCMC: Int64 25
  Tmin: Float64 0.05
  Tmax: Float64 1.0
  nT: Int64 100
  cooling_schedule: Symbol geometric
  Trange: Array{Float64}((101,)) [1.0, 0.9704869503929601, 0.9418449208830277, 0.9140482050108684, 0.8870718549931568, 0.8608916593317348, 0.8354841210835904, 0.8108264367721563, 0.7868964759210002, 0.7636727611915388  …  0.06547306980281228, 0.0635407598457967, 0.06166547824839869, 0.059845541929811855, 0.05807931748207713, 0.05636521970408556, 0.05470171017884719, 0.053087295892748944, 0.05152052789556264, 0.05000000000000001]
  sa_rep: Int64 1
  verbose: Bool true
  vv: Bool false

/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/cli.jl:95 [Info] Inferring MCCs...

/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:75 [Info] Initial state: 41 naive MCCs
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:82 [Info] --- Iteration 1 (max. 15) - 100 leaves remaining ---

/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:85 [Info] Running optimization to find MCCs...
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:86 [Info] Cooling schedule: geometric / Temperature values: 101 / Total of MCMC steps: 2500
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/SplitGraph/SplitGraph.jl:70 [Info] Sorting 2 topologically equivalent configurations.
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/SplitGraph/SplitGraph.jl:101 [Info] Comparing 2 configurations using likelihood
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:95 [Info] Found 8 new mccs.
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:99 [Info] Proceeding based on newly found MCCs...
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:152 [Info] Found mccs do not cover all leaves. Pruning them from trees.
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:174 [Info] Resulting trees have incompatibilities (14 naive mccs left). Continuing.

/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:82 [Info] --- Iteration 2 (max. 15) - 75 leaves remaining ---

/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:85 [Info] Running optimization to find MCCs...
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:86 [Info] Cooling schedule: geometric / Temperature values: 101 / Total of MCMC steps: 1875
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:95 [Info] Found 4 new mccs.
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:99 [Info] Proceeding based on newly found MCCs...
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:152 [Info] Found mccs do not cover all leaves. Pruning them from trees.
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:174 [Info] Resulting trees have incompatibilities (7 naive mccs left). Continuing.

/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:82 [Info] --- Iteration 3 (max. 15) - 60 leaves remaining ---

/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:85 [Info] Running optimization to find MCCs...
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:86 [Info] Cooling schedule: geometric / Temperature values: 101 / Total of MCMC steps: 1500
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/SplitGraph/SplitGraph.jl:70 [Info] Sorting 2 topologically equivalent configurations.
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/SplitGraph/SplitGraph.jl:101 [Info] Comparing 2 configurations using likelihood
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:95 [Info] Found 2 new mccs.
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:99 [Info] Proceeding based on newly found MCCs...
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:152 [Info] Found mccs do not cover all leaves. Pruning them from trees.
/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/main.jl:163 [Info] Resulting trees are compatible: final decomposition found. Stopping.

/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/cli.jl:98 [Info] Found 15 MCCs (runtime 2.005045834)

/Users/xmwei/.julia/packages/TreeKnit/gOfL1/src/cli.jl:102 [Info] Resolving trees based on found MCCs...

**Comment by PierreBarrat** [comment]
Can you try updating TreeKnit to v0.3.3? it should be fixed there.
You may have to re-build the package after updating to change the `treeknit` executable. Something like 
```
]update # should update to v0.3.3
]build TreeKnit
```

**Comment by Xiaoman-Wei** [comment]
> 

Thanks! It works after updating TreeKnit to v0.3.3!

**Comment by PierreBarrat** [comment]
Great! I had made some changes to TreeTools (dependency), but had not pushed the new TreeKnit to the general registry ... 
Thanks for your interest, hope you'll find TreeKnit useful !
